/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#173124',
        'on-primary': '#ffffff',
        'primary-container': '#2d4739',
        'on-primary-container': '#98b5a3',
        'primary-fixed': '#ccead6',
        'primary-fixed-dim': '#b0cdbb',
        'on-primary-fixed': '#062014',
        'on-primary-fixed-variant': '#324c3e',
        'inverse-primary': '#b0cdbb',
        'secondary': '#5f5e5b',
        'on-secondary': '#ffffff',
        'secondary-container': '#e5e2dd',
        'on-secondary-container': '#656461',
        'secondary-fixed': '#e5e2dd',
        'secondary-fixed-dim': '#c9c6c2',
        'on-secondary-fixed': '#1c1c19',
        'on-secondary-fixed-variant': '#474743',
        'tertiary': '#202f20',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#354635',
        'on-tertiary-container': '#a1b39e',
        'tertiary-fixed': '#d5e8d1',
        'tertiary-fixed-dim': '#b9ccb5',
        'on-tertiary-fixed': '#101f11',
        'on-tertiary-fixed-variant': '#3a4b3a',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#fbf9f8',
        'on-background': '#1b1c1c',
        'surface': '#fbf9f8',
        'on-surface': '#1b1c1c',
        'surface-variant': '#e4e2e1',
        'on-surface-variant': '#424844',
        'surface-bright': '#fbf9f8',
        'surface-dim': '#dcd9d9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae8e7',
        'surface-container-highest': '#e4e2e1',
        'surface-tint': '#496455',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f3f0f0',
        'outline': '#727973',
        'outline-variant': '#c2c8c2',
      },
      spacing: {
        'xs': '4px',
        'sm': '12px',
        'base': '8px',
        'md': '24px',
        'gutter': '24px',
        'lg': '48px',
        'xl': '80px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'container-max': '1280px',
        'container-padding': '40px',
        'section-gap': '64px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        'display-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'headline-xl': ['Manrope', 'sans-serif'],
        'headline-xl-mobile': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'headline-lg-mobile': ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-sm': ['Manrope', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
